name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  lint:
    name: Prettier lint check
    uses: bgd-labs/github-workflows/.github/workflows/foundry-lint-prettier.yml@main
  test:
    name: Foundry build n test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: bgd-labs/action-rpc-env@5191193b0de7443bda94b6f42092c83e32464adc
        with:
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          QUICKNODE_TOKEN: ${{ secrets.QUICKNODE_TOKEN }}
          QUICKNODE_ENDPOINT_NAME: ${{ secrets.QUICKNODE_ENDPOINT_NAME }}

      - uses: bgd-labs/github-workflows/.github/actions/foundry-setup@main

      - uses: bgd-labs/github-workflows/.github/actions/setup-node@main

      - name: Run Forge size
        uses: bgd-labs/github-workflows/.github/actions/foundry-size@main
        continue-on-error: true

      - name: Run Gas report
        uses: bgd-labs/github-workflows/.github/actions/foundry-gas-report@main

      - name: Run Forge tests
        uses: bgd-labs/github-workflows/.github/actions/foundry-test@main

      - name: Run Generator tests
        run: pnpm run test

      - name: Upload & Trigger Comment artifact
        uses: bgd-labs/github-workflows/.github/actions/comment-artifact@main
        with:
          nameSuffix: "default"
